-- Migration: Create AI Agent Tables
-- Date: 2026-03-27
-- Description: Create database schema for AI Agent Dashboard

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- AI Agent Logs Table
-- ============================================================================
-- Stores all AI Agent operations and interactions
CREATE TABLE IF NOT EXISTS ai_agent_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  service_type VARCHAR(50) NOT NULL,  -- 'email', 'zalo', 'scoring', 'task'
  action VARCHAR(100) NOT NULL,       -- 'generate', 'send', 'calculate', 'assign'
  input_data JSONB,                   -- Input parameters for the action
  output_data JSONB,                  -- Output/result from the action
  gemini_tokens_used INT,             -- Number of tokens used from Gemini API
  gemini_model VARCHAR(50),           -- Model used (e.g., 'gemini-2.5-flash')
  status VARCHAR(20) NOT NULL,        -- 'success', 'failed', 'pending'
  error_message TEXT,                 -- Error details if status is 'failed'
  duration_ms INT,                    -- Execution time in milliseconds
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_agent_logs_lead_id ON ai_agent_logs(lead_id);
CREATE INDEX idx_ai_agent_logs_service_type ON ai_agent_logs(service_type);
CREATE INDEX idx_ai_agent_logs_created_at ON ai_agent_logs(created_at DESC);

-- ============================================================================
-- Email Tracking Table
-- ============================================================================
-- Tracks email sending and engagement metrics
CREATE TABLE IF NOT EXISTS email_tracking (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  email_id VARCHAR(100) NOT NULL UNIQUE,  -- Email provider's message ID
  subject TEXT NOT NULL,
  body_preview TEXT,
  email_type VARCHAR(50),             -- 'chao_hang', 'follow_up', 'quote', 'thank_you'
  sent_at TIMESTAMP NOT NULL,
  opened_at TIMESTAMP,
  first_click_at TIMESTAMP,
  last_click_at TIMESTAMP,
  converted_at TIMESTAMP,
  bounced_at TIMESTAMP,
  unsubscribed_at TIMESTAMP,
  click_count INT DEFAULT 0,
  tracking_id VARCHAR(100),           -- Unique tracking identifier
  provider VARCHAR(50),               -- 'gmail', 'sendgrid', 'smtp'
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_email_tracking_lead_id ON email_tracking(lead_id);
CREATE INDEX idx_email_tracking_sent_at ON email_tracking(sent_at DESC);
CREATE INDEX idx_email_tracking_email_type ON email_tracking(email_type);

-- ============================================================================
-- Zalo Conversations Table
-- ============================================================================
-- Stores Zalo chat messages and interactions
CREATE TABLE IF NOT EXISTS zalo_conversations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  message_id VARCHAR(100) NOT NULL UNIQUE,
  role VARCHAR(20) NOT NULL,         -- 'user', 'assistant'
  content TEXT NOT NULL,
  intent VARCHAR(50),                -- Detected intent (e.g., 'price_inquiry', 'product_info')
  intent_confidence DECIMAL(3, 2),   -- Confidence score (0.0 - 1.0)
  entities JSONB,                    -- Extracted entities from message
  sentiment VARCHAR(20),             -- 'positive', 'neutral', 'negative'
  source VARCHAR(50),                -- 'zalo_api', 'ai_agent'
  ai_generated BOOLEAN DEFAULT FALSE, -- Whether response was generated by AI
  gemini_tokens_used INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_zalo_conversations_lead_id ON zalo_conversations(lead_id);
CREATE INDEX idx_zalo_conversations_created_at ON zalo_conversations(created_at DESC);
CREATE INDEX idx_zalo_conversations_intent ON zalo_conversations(intent);

-- ============================================================================
-- Lead Scores Table
-- ============================================================================
-- Stores lead scoring history and classification
CREATE TABLE IF NOT EXISTS lead_scores (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  score INT NOT NULL CHECK (score >= 0 AND score <= 100),
  classification VARCHAR(20) NOT NULL,  -- 'hot', 'warm', 'cold'
  
  -- Scoring factors breakdown
  engagement_score INT,
  recency_score INT,
  source_quality_score INT,
  company_profile_score INT,
  
  -- Engagement metrics
  emails_opened INT DEFAULT 0,
  emails_clicked INT DEFAULT 0,
  website_visits INT DEFAULT 0,
  chat_messages INT DEFAULT 0,
  quotes_viewed INT DEFAULT 0,
  days_active INT DEFAULT 0,
  
  -- Factors used in calculation
  factors JSONB,                     -- Detailed breakdown of all factors
  recommendations JSONB,             -- Array of recommended next actions
  
  -- Prediction
  predicted_score_30days INT,
  predicted_classification_30days VARCHAR(20),
  prediction_confidence DECIMAL(3, 2),
  
  calculated_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_lead_scores_lead_id ON lead_scores(lead_id);
CREATE INDEX idx_lead_scores_classification ON lead_scores(classification);
CREATE INDEX idx_lead_scores_calculated_at ON lead_scores(calculated_at DESC);

-- ============================================================================
-- AI Tasks Table
-- ============================================================================
-- Stores automatically generated tasks for follow-up
CREATE TABLE IF NOT EXISTS ai_tasks (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  assigned_to UUID REFERENCES staff(id) ON DELETE SET NULL,
  
  task_type VARCHAR(50) NOT NULL,    -- 'follow_up_call', 'send_email', 'schedule_meeting', 'send_quote'
  title TEXT NOT NULL,
  description TEXT,
  
  priority VARCHAR(20) NOT NULL,     -- 'high', 'medium', 'low'
  estimated_duration_minutes INT,    -- Estimated time to complete
  
  status VARCHAR(20) NOT NULL DEFAULT 'pending',  -- 'pending', 'assigned', 'in_progress', 'completed', 'cancelled'
  
  due_date TIMESTAMP NOT NULL,
  completed_at TIMESTAMP,
  
  -- Assignment details
  assignment_reason TEXT,            -- Why this task was suggested
  assignment_score DECIMAL(3, 2),    -- Score for this assignment (0.0 - 1.0)
  
  -- Reminders
  reminder_1hour BOOLEAN DEFAULT FALSE,
  reminder_30min BOOLEAN DEFAULT FALSE,
  reminder_5min BOOLEAN DEFAULT FALSE,
  
  -- Auto-generated indicator
  ai_generated BOOLEAN DEFAULT TRUE,
  gemini_tokens_used INT,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_tasks_lead_id ON ai_tasks(lead_id);
CREATE INDEX idx_ai_tasks_assigned_to ON ai_tasks(assigned_to);
CREATE INDEX idx_ai_tasks_status ON ai_tasks(status);
CREATE INDEX idx_ai_tasks_due_date ON ai_tasks(due_date);
CREATE INDEX idx_ai_tasks_priority ON ai_tasks(priority);

-- ============================================================================
-- AI Agent Settings Table
-- ============================================================================
-- Stores configuration and settings for AI Agent
CREATE TABLE IF NOT EXISTS ai_agent_settings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  setting_key VARCHAR(100) NOT NULL UNIQUE,
  setting_value JSONB NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default settings
INSERT INTO ai_agent_settings (setting_key, setting_value, description) VALUES
  ('email_triggers', '{"new_lead": true, "no_interaction_3days": true, "quote_sent": true, "successful_close": true}', 'Email automation triggers'),
  ('zalo_auto_reply', '{"enabled": true, "escalation_threshold": 3}', 'Zalo chatbot settings'),
  ('lead_scoring_weights', '{"engagement": 0.35, "recency": 0.25, "source_quality": 0.20, "company_profile": 0.20}', 'Lead scoring algorithm weights'),
  ('task_assignment_strategy', '{"method": "workload_based", "max_tasks_per_staff": 10}', 'Task assignment strategy'),
  ('gemini_model', '{"model": "gemini-2.5-flash", "max_tokens": 1000, "temperature": 0.7}', 'Gemini API configuration')
ON CONFLICT (setting_key) DO NOTHING;

-- ============================================================================
-- AI Agent Usage Statistics Table
-- ============================================================================
-- Tracks API usage and performance metrics
CREATE TABLE IF NOT EXISTS ai_agent_usage_stats (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  date DATE NOT NULL,
  
  -- Email metrics
  emails_generated INT DEFAULT 0,
  emails_sent INT DEFAULT 0,
  emails_opened INT DEFAULT 0,
  email_open_rate DECIMAL(5, 2),
  
  -- Zalo metrics
  zalo_messages_received INT DEFAULT 0,
  zalo_messages_replied INT DEFAULT 0,
  zalo_auto_reply_rate DECIMAL(5, 2),
  
  -- Scoring metrics
  leads_scored INT DEFAULT 0,
  leads_hot INT DEFAULT 0,
  leads_warm INT DEFAULT 0,
  leads_cold INT DEFAULT 0,
  
  -- Task metrics
  tasks_generated INT DEFAULT 0,
  tasks_completed INT DEFAULT 0,
  task_completion_rate DECIMAL(5, 2),
  
  -- API usage
  total_gemini_tokens_used INT DEFAULT 0,
  total_api_calls INT DEFAULT 0,
  average_response_time_ms INT,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_agent_usage_stats_date ON ai_agent_usage_stats(date DESC);

-- ============================================================================
-- Create Views for Dashboard
-- ============================================================================

-- View: Recent AI Agent Activities
CREATE OR REPLACE VIEW v_recent_ai_activities AS
SELECT 
  'email' as activity_type,
  l.id as lead_id,
  l.name as lead_name,
  et.subject as activity_detail,
  et.sent_at as activity_time,
  CASE WHEN et.opened_at IS NOT NULL THEN 'opened' ELSE 'sent' END as status
FROM email_tracking et
JOIN leads l ON et.lead_id = l.id
UNION ALL
SELECT 
  'zalo' as activity_type,
  l.id as lead_id,
  l.name as lead_name,
  zc.content as activity_detail,
  zc.created_at as activity_time,
  CASE WHEN zc.role = 'assistant' THEN 'replied' ELSE 'received' END as status
FROM zalo_conversations zc
JOIN leads l ON zc.lead_id = l.id
UNION ALL
SELECT 
  'task' as activity_type,
  l.id as lead_id,
  l.name as lead_name,
  at.title as activity_detail,
  at.created_at as activity_time,
  at.status
FROM ai_tasks at
JOIN leads l ON at.lead_id = l.id
ORDER BY activity_time DESC;

-- View: Lead Score Summary
CREATE OR REPLACE VIEW v_lead_score_summary AS
SELECT 
  l.id,
  l.name,
  ls.score,
  ls.classification,
  ls.engagement_score,
  ls.recency_score,
  ls.source_quality_score,
  ls.company_profile_score,
  ls.calculated_at,
  CASE 
    WHEN ls.classification = 'hot' THEN 1
    WHEN ls.classification = 'warm' THEN 2
    ELSE 3
  END as priority_order
FROM leads l
LEFT JOIN lead_scores ls ON l.id = ls.lead_id
WHERE ls.id IN (
  SELECT id FROM lead_scores 
  WHERE lead_id = l.id 
  ORDER BY calculated_at DESC 
  LIMIT 1
);

-- View: AI Agent Performance Metrics
CREATE OR REPLACE VIEW v_ai_agent_performance AS
SELECT 
  date,
  emails_sent,
  email_open_rate,
  zalo_messages_replied,
  zalo_auto_reply_rate,
  leads_scored,
  leads_hot,
  leads_warm,
  leads_cold,
  tasks_generated,
  task_completion_rate,
  total_gemini_tokens_used,
  total_api_calls,
  average_response_time_ms
FROM ai_agent_usage_stats
ORDER BY date DESC;

-- ============================================================================
-- Create Triggers for Automatic Updates
-- ============================================================================

-- Update ai_agent_logs.updated_at
CREATE OR REPLACE FUNCTION update_ai_agent_logs_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_ai_agent_logs_timestamp
BEFORE UPDATE ON ai_agent_logs
FOR EACH ROW
EXECUTE FUNCTION update_ai_agent_logs_timestamp();

-- Update email_tracking.updated_at
CREATE OR REPLACE FUNCTION update_email_tracking_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_email_tracking_timestamp
BEFORE UPDATE ON email_tracking
FOR EACH ROW
EXECUTE FUNCTION update_email_tracking_timestamp();

-- Update lead_scores.updated_at
CREATE OR REPLACE FUNCTION update_lead_scores_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_lead_scores_timestamp
BEFORE UPDATE ON lead_scores
FOR EACH ROW
EXECUTE FUNCTION update_lead_scores_timestamp();

-- Update ai_tasks.updated_at
CREATE OR REPLACE FUNCTION update_ai_tasks_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_ai_tasks_timestamp
BEFORE UPDATE ON ai_tasks
FOR EACH ROW
EXECUTE FUNCTION update_ai_tasks_timestamp();

-- ============================================================================
-- Grant Permissions
-- ============================================================================

-- Grant permissions to application user (adjust user name as needed)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ai_agent_logs TO app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON email_tracking TO app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON zalo_conversations TO app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON lead_scores TO app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ai_tasks TO app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ai_agent_settings TO app_user;
-- GRANT SELECT, INSERT, UPDATE ON ai_agent_usage_stats TO app_user;
-- GRANT SELECT ON v_recent_ai_activities TO app_user;
-- GRANT SELECT ON v_lead_score_summary TO app_user;
-- GRANT SELECT ON v_ai_agent_performance TO app_user;
