import type { GoogleAdsProduct } from "./types";

export const SMARTFURNI_AD_PRODUCTS_SEED_VERSION = "2026-06-25T08:00:00.000Z";

const now = SMARTFURNI_AD_PRODUCTS_SEED_VERSION;

export const SMARTFURNI_AD_PRODUCTS: GoogleAdsProduct[] = [
  {
    id: "smf12",
    sku: "SMF12",
    name: "Sofa giường thông minh SMF12",
    productLine: "sofa_giuong",
    price: 12800000,
    size: "1m2 x 1m9, tùy chỉnh theo yêu cầu",
    material: "Khung thép sơn tĩnh điện, nệm bọc vải cao cấp",
    usp: ["Tiết kiệm diện tích", "Đặt size, màu theo yêu cầu", "Giao lắp tận nơi", "Bảo hành 5 năm"],
    targetCustomers: ["Căn hộ nhỏ", "Nhà có khách ở lại", "Gia đình trẻ"],
    landingPageUrl: "https://www.smartfurni.com.vn/sofa-giuong-thong-minh",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smf23",
    sku: "SMF23",
    name: "Sofa giường thông minh SMF23",
    productLine: "sofa_giuong",
    price: 15600000,
    size: "1m4 x 2m, tùy chỉnh theo yêu cầu",
    material: "Khung thép chắc chắn, nệm mousse D40, vải/da tùy chọn",
    usp: ["Mở gấp gọn", "Phù hợp căn hộ nhỏ", "Sản xuất tại Việt Nam", "Bảo hành 5 năm"],
    targetCustomers: ["Căn hộ chung cư", "Phòng khách nhỏ", "Homestay"],
    landingPageUrl: "https://www.smartfurni.com.vn/sofa-giuong-thong-minh/smf23",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smf18",
    sku: "SMF18",
    name: "Sofa giường thông minh SMF18",
    productLine: "sofa_giuong",
    price: 18500000,
    size: "1m6 x 2m, tùy chỉnh theo yêu cầu",
    material: "Khung thép, cơ cấu nâng hạ, nệm bọc nỉ/da",
    usp: ["Chuyển sofa và giường nhanh", "Giao lắp tận nơi", "Chọn màu theo nội thất", "Bảo hành 5 năm"],
    targetCustomers: ["Gia đình cần thêm chỗ ngủ", "Căn hộ studio", "Phòng đa năng"],
    landingPageUrl: "https://www.smartfurni.com.vn/sofa-giuong-thong-minh/smf18",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smf450",
    sku: "SMF450",
    name: "Giường công thái học SMF450",
    productLine: "giuong_cong_thai_hoc",
    price: 32500000,
    size: "1m6/1m8 x 2m",
    material: "Khung thép nâng hạ điện, đệm foam cao cấp",
    usp: ["Nâng hạ đầu và chân", "Remote điều khiển", "Khung thép chắc chắn", "Bảo hành 5 năm"],
    targetCustomers: ["Người cần tư thế đọc sách, xem TV", "Gia đình hiện đại", "Căn hộ cao cấp"],
    landingPageUrl: "https://www.smartfurni.com.vn/giuong-thong-minh-cong-thai-hoc",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gsf150",
    sku: "GSF150",
    name: "Khung giường nâng hạ GSF150",
    productLine: "giuong_cong_thai_hoc",
    price: 21900000,
    size: "1m5/1m6/1m8 x 2m",
    material: "Khung thép sơn tĩnh điện, motor nâng hạ êm",
    usp: ["Lắp với nệm hiện có", "Điều chỉnh tư thế linh hoạt", "Sản xuất tại Việt Nam", "Giao lắp tận nơi"],
    targetCustomers: ["Khách đã có nệm", "Gia đình muốn nâng cấp phòng ngủ", "Căn hộ hiện đại"],
    landingPageUrl: "https://www.smartfurni.com.vn/khung-giuong-nang-ha",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gyt300",
    sku: "GYT300",
    name: "Giường y tế tại nhà GYT300",
    productLine: "giuong_y_te",
    price: 28500000,
    size: "0m9/1m2 x 2m",
    material: "Khung thép y tế, thành chắn an toàn, motor nâng hạ",
    usp: ["Hỗ trợ chăm sóc tại nhà", "Nâng hạ đầu chân", "Thành chắn an toàn", "Giao lắp tận nơi"],
    targetCustomers: ["Gia đình chăm sóc người lớn tuổi", "Phòng chăm sóc tại nhà", "Phòng khám"],
    landingPageUrl: "https://www.smartfurni.com.vn/giuong-y-te-tai-nha",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
];
