import type { GoogleAdsProduct } from "./types";

const now = "2026-06-23T00:00:00.000Z";

export const SMARTFURNI_AD_PRODUCTS: GoogleAdsProduct[] = [
  {
    id: "smf12",
    sku: "SMF12",
    name: "Sofa giuong thong minh SMF12",
    productLine: "sofa_giuong",
    price: 12800000,
    size: "1m2 x 1m9, tuy chinh theo yeu cau",
    material: "Khung thep son tinh dien, nem boc vai cao cap",
    usp: ["Tiet kiem dien tich", "Dat size mau theo yeu cau", "Giao lap tan noi", "Bao hanh 5 nam"],
    targetCustomers: ["Can ho nho", "Nha co khach o lai", "Gia dinh tre"],
    landingPageUrl: "https://smartfurni.vn/sofa-giuong-thong-minh",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smf23",
    sku: "SMF23",
    name: "Sofa giuong thong minh SMF23",
    productLine: "sofa_giuong",
    price: 15600000,
    size: "1m4 x 2m, tuy chinh theo yeu cau",
    material: "Khung thep chac chan, nem mousse D40, vai/da tuy chon",
    usp: ["Mo gap gon", "Phu hop can ho nho", "San xuat tai Viet Nam", "Bao hanh 5 nam"],
    targetCustomers: ["Can ho chung cu", "Phong khach nho", "Homestay"],
    landingPageUrl: "https://smartfurni.vn/sofa-giuong-thong-minh/smf23",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smf18",
    sku: "SMF18",
    name: "Sofa giuong thong minh SMF18",
    productLine: "sofa_giuong",
    price: 18500000,
    size: "1m6 x 2m, tuy chinh theo yeu cau",
    material: "Khung thep, co cau nang ha, nem boc ni/da",
    usp: ["Thanh sofa va giuong nhanh", "Giao lap tan noi", "Chon mau theo noi that", "Bao hanh 5 nam"],
    targetCustomers: ["Gia dinh can them cho ngu", "Can ho studio", "Phong da nang"],
    landingPageUrl: "https://smartfurni.vn/sofa-giuong-thong-minh/smf18",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "smf450",
    sku: "SMF450",
    name: "Giuong cong thai hoc SMF450",
    productLine: "giuong_cong_thai_hoc",
    price: 32500000,
    size: "1m6/1m8 x 2m",
    material: "Khung thep nang ha dien, dem foam cao cap",
    usp: ["Nang ha dau va chan", "Remote dieu khien", "Khung thep chac chan", "Bao hanh 5 nam"],
    targetCustomers: ["Nguoi can tu the doc sach xem TV", "Gia dinh hien dai", "Can ho cao cap"],
    landingPageUrl: "https://smartfurni.vn/giuong-thong-minh-cong-thai-hoc",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gsf150",
    sku: "GSF150",
    name: "Khung giuong nang ha GSF150",
    productLine: "giuong_cong_thai_hoc",
    price: 21900000,
    size: "1m5/1m6/1m8 x 2m",
    material: "Khung thep son tinh dien, motor nang ha em",
    usp: ["Lap voi nem hien co", "Dieu chinh tu the linh hoat", "San xuat tai Viet Nam", "Giao lap tan noi"],
    targetCustomers: ["Khach da co nem", "Gia dinh muon nang cap phong ngu", "Can ho hien dai"],
    landingPageUrl: "https://smartfurni.vn/khung-giuong-nang-ha",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "gyt300",
    sku: "GYT300",
    name: "Giuong y te tai nha GYT300",
    productLine: "giuong_y_te",
    price: 28500000,
    size: "0m9/1m2 x 2m",
    material: "Khung thep y te, thanh chan an toan, motor nang ha",
    usp: ["Ho tro cham soc tai nha", "Nang ha dau chan", "Thanh chan an toan", "Giao lap tan noi"],
    targetCustomers: ["Gia dinh cham soc nguoi lon tuoi", "Phong cham soc tai nha", "Phong kham"],
    landingPageUrl: "https://smartfurni.vn/giuong-y-te-tai-nha",
    status: "active",
    createdAt: now,
    updatedAt: now,
  },
];
